# Generated by Django 4.2 on 2023-05-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Broadcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broad',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AddField(
            model_name='broad',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
